spring:
   jpa:
      show-sql: true
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      user: sa
management:
    endpoints:
        enabled-by-default: false
        web:
            base-path: /api/genericDal/v1
            path-mapping:
              health: health
    endpoint:
        health.enabled: true
        health.show-details: always 
server: 
   port: 8080
